Projects/Movie/movieproject/movieapp/urls.py
from .import views
from django.urls import path,include
app_name="movieapp"
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

Projects/Movie/movieproject/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Projects/Movie/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

Projects/Movie/movieproject/movieapp/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

Projects/Movie/movieproject/movieapp/views.py
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm


# Create your views here.


def index(request):
    movie=Movie.objects.all()
    context={'movie_list':movie}
    return render(request,"index.html",context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=="POST":
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

Projects/Movie/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container mt-5">
    <div class="row ">
        <div class="col-2">
             Movie Name:
        </div>
        <div class="col-4">
            <input type="text" class="form-control" name="name" placeholder="Enter the name">
        </div>
    </div>
        <div class="row my-4">
        <div class="col-2">
             <label>Description:</label>
        </div>
        <div class="col-4">
            <textarea class="form-control" rows="3" name="desc" placeholder="Enter the description"></textarea>
        </div>
        </div>
        <div class="row my-4 ">
        <div class="col-2">
             <label>Year:</label>

        </div>
        <div class="col-4">
            <input type="text" class="form-control" name="year" placeholder="Enter the year">
        </div>
        </div>
        <div class="row my-4">
        <div class="col-2">
             <label>Image:</label>
        </div>
        <div class="col-4">
            <input type="file" class="form-control-file" name="img" >
        </div>
        </div>
        <div class="row my-4">
            <div class="col-2"></div>
            <div class="col-4">
            <input type="submit" class="btn btn-primary">
        </div>
    </div>

    </div>
</form>
{% endblock %}

Projects/Movie/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color: rgba(13, 110, 253, .25);" >
<nav class="navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
     Movie Store
    </a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

Projects/Movie/movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container text-center mt-5">
        <h4 >Are yo sure to delete this movie?</h4>
    <input type="submit" class="btn btn-primary ">
    </div>

</form>
{% endblock %}

Projects/Movie/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid mt-5" xmlns="http://www.w3.org/1999/html">
     <div class="row">
    <div class="col-md-4 m-2">
        <img src="{{movie.img.url}}" width="500" height="500">
    </div>
    <div class="col-md-4 mx-4 ">
        <h1><b><u>{{movie.name}}</u></b></h1><br>
        <h4>{{movie.desc}}</h4><br>
        <h3><b><i>{{movie.year}}</b></i></h3><br>
        <a class="btn btn-info " href="{% url 'movieapp:update' movie.id %}">UPDATE</a>
        <a class="btn btn-danger mx-3" href="{% url 'movieapp:delete' movie.id %}">DELETE</a>
    </div>
  </div>

</div>




{% endblock %}

Projects/Movie/movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="container mt-5">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="card bg-light text-dark">
                    <div class="card-body ">
                        {{ form.as_p }}
                        <div class="row mt-4">
                            <div class="col-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
{% endblock %}

Projects/Movie/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
  <div class="row">
      {% for i in movie_list %}
      <div class="card m-4" style="width: 18rem;">
  <img src="{{i.img.url}}" class="card-img-top mt-2" width="100%" height="100%">
  <div class="card-body">
      <h2 class="card-title"><b>{{i.name}}</b></h2>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">More details</a>
  </div>
</div>
      {% endfor %}
  </div>
</div>



{% endblock %}